window.PARFAIT_CATALOGUE = {
  "version": 1,
  "updated": "2026-09-01T14:46:04.324Z",
  "items": [
    {
      "id": "msgp527nmr7my",
      "kind": "wallpaper",
      "brand": "York Wallcoverings",
      "pattern": "Antonina Vella Deco Speakeasy",
      "colorway": "",
      "room": "Office",
      "style": "Metallic",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/york-wallcoverings-antonina-vella-deco-speakeasy-r7my.jpg",
        "photos/york-wallcoverings-antonina-vella-deco-speakeasy-r7my-bw7.jpg",
        "photos/york-wallcoverings-antonina-vella-deco-speakeasy-r7my-hsc.jpg"
      ],
      "cover": 1,
      "photo": "photos/york-wallcoverings-antonina-vella-deco-speakeasy-r7my-bw7.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msgqt1vq5xyi2",
      "kind": "wallpaper",
      "brand": "Wallism",
      "pattern": "Ukiyo-e Clouds, Blues wallpaper mural",
      "colorway": "",
      "room": "Living room",
      "style": "Mural & scenic",
      "project": "",
      "city": "Atherton",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2.jpg",
        "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2-3rd.jpg",
        "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2-4o7.jpg",
        "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2-1k2.jpg"
      ],
      "cover": 0,
      "photo": "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msqeu91xtlx2t",
      "kind": "wallpaper",
      "brand": "Kelly Ventura",
      "pattern": "Marsh in Lagoon",
      "colorway": "",
      "room": "Living room",
      "style": "Floral",
      "project": "",
      "city": "Belmont",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-jev.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-hsa.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-0il.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-o04.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-9w8.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-41q.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-w1l.jpg"
      ],
      "cover": 3,
      "photo": "photos/kelly-ventura-marsh-in-lagoon-lx2t-o04.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msrm2hpqkvfom",
      "kind": "wallpaper",
      "brand": "York Wallcoverings",
      "pattern": "York Modern Heritage Yarrow Nouveau",
      "colorway": "Charcoal & Gold",
      "room": "Primary bedroom",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/york-wallcoverings-york-modern-heritage-yarrow-nouveau-vfom-y09.jpg",
        "photos/york-wallcoverings-york-modern-heritage-yarrow-nouveau-vfom-n1t.jpg",
        "photos/york-wallcoverings-york-modern-heritage-yarrow-nouveau-vfom-28n.jpg"
      ],
      "cover": 0,
      "photo": "photos/york-wallcoverings-york-modern-heritage-yarrow-nouveau-vfom-y09.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msrmoagz15cu4",
      "kind": "wallpaper",
      "brand": "York Wallcoverings",
      "pattern": "Gwendolyn Wallpaper - Magnolia Home collection by Joanna Gaines,",
      "colorway": "",
      "room": "Laundry room",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-xnd.jpg",
        "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-tpv.jpg",
        "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-yht.jpg",
        "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-rm3.jpg"
      ],
      "cover": 0,
      "photo": "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-xnd.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msrowrdmrh7dx",
      "kind": "wallpaper",
      "brand": "Phillip Jeffries",
      "pattern": "Fuji Weave - Fresh Stream",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Grasscloth & texture",
      "project": "",
      "city": "Corte Madera",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-9t9.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-8pj.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-k1e.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-i1w.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-7gi.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-eg7.jpg"
      ],
      "cover": 2,
      "photo": "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-k1e.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss0m5aiji456",
      "kind": "wallpaper",
      "brand": "Happy Wall",
      "pattern": "Dandelion Dreamscape",
      "colorway": "",
      "room": "Bathroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Mateo",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/happy-wall-dandelion-dreamscape-i456-uji.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-v31.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-3yj.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-gkp.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-5sw.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-jip.jpg"
      ],
      "cover": 0,
      "photo": "photos/happy-wall-dandelion-dreamscape-i456-uji.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss1jilh0x9nl",
      "kind": "wallpaper",
      "brand": "Phillip Jeffries",
      "pattern": "Aura Ivory",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Rafael - Marinwood",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/phillip-jeffries-aura-ivory-x9nl-ceh.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-sh1.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-n14.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-nyi.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-cul.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-gnt.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-py8.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-k6m.jpg"
      ],
      "cover": 0,
      "photo": "photos/phillip-jeffries-aura-ivory-x9nl-ceh.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss1scrkeqby5",
      "kind": "wallpaper",
      "brand": "Spoonflower",
      "pattern": "Art Deco Swans",
      "colorway": "Black on cream",
      "room": "Sitting room",
      "style": "Pattern",
      "project": "",
      "city": "",
      "year": "2025",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/spoonflower-art-deco-swans-qby5-ije.jpg",
        "photos/spoonflower-art-deco-swans-qby5-9sl.jpg",
        "photos/spoonflower-art-deco-swans-qby5-ze5.jpg",
        "photos/spoonflower-art-deco-swans-qby5-p0j.jpg"
      ],
      "cover": 0,
      "photo": "photos/spoonflower-art-deco-swans-qby5-ije.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss24arga0pmm",
      "kind": "wallpaper",
      "brand": "Hygge & West",
      "pattern": "Underwater World Wallpaper",
      "colorway": "Deep Blue",
      "room": "Guest bathroom",
      "style": "Metallic",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/hygge-west-underwater-world-wallpaper-0pmm-rqm.jpg",
        "photos/hygge-west-underwater-world-wallpaper-0pmm-akt.jpg",
        "photos/hygge-west-underwater-world-wallpaper-0pmm-9ab.jpg",
        "photos/hygge-west-underwater-world-wallpaper-0pmm-x82.jpg"
      ],
      "cover": 3,
      "photo": "photos/hygge-west-underwater-world-wallpaper-0pmm-x82.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss2ft9wam76c",
      "kind": "wallpaper",
      "brand": "Sandberg",
      "pattern": "Klint Misty Blue Wallpaper Mural",
      "colorway": "",
      "room": "Office",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/sandberg-klint-misty-blue-wallpaper-mural-m76c-2fq.jpg",
        "photos/sandberg-klint-misty-blue-wallpaper-mural-m76c-6e5.jpg"
      ],
      "cover": 0,
      "photo": "photos/sandberg-klint-misty-blue-wallpaper-mural-m76c-2fq.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss2lbajqqjo4",
      "kind": "wallpaper",
      "brand": "Rebel Walls",
      "pattern": "Flowing Hills",
      "colorway": "Green",
      "room": "Office",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/rebel-walls-flowing-hills-qjo4-x8p.jpg",
        "photos/rebel-walls-flowing-hills-qjo4-869.jpg",
        "photos/rebel-walls-flowing-hills-qjo4-wcp.jpg",
        "photos/rebel-walls-flowing-hills-qjo4-8uj.jpg",
        "photos/rebel-walls-flowing-hills-qjo4-oq0.jpg"
      ],
      "cover": 0,
      "photo": "photos/rebel-walls-flowing-hills-qjo4-x8p.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss2ww0p7xrp9",
      "kind": "wallpaper",
      "brand": "York Wallcoverings",
      "pattern": "Judarn Floral Mural",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Mural & scenic",
      "project": "2025",
      "city": "",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/york-wallcoverings-judarn-floral-mural-2025-xrp9-7xl.jpg",
        "photos/york-wallcoverings-judarn-floral-mural-2025-xrp9-0uo.jpg",
        "photos/york-wallcoverings-judarn-floral-mural-2025-xrp9-dfc.jpg"
      ],
      "cover": 0,
      "photo": "photos/york-wallcoverings-judarn-floral-mural-2025-xrp9-7xl.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss31howbaabb",
      "kind": "wallpaper",
      "brand": "Belarte",
      "pattern": "Vintage Landscape",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Francisco",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/belarte-vintage-landscape-aabb-ixc.jpg",
        "photos/belarte-vintage-landscape-aabb-l4t.jpg",
        "photos/belarte-vintage-landscape-aabb-91q.jpg"
      ],
      "cover": 2,
      "photo": "photos/belarte-vintage-landscape-aabb-91q.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss7d96dndn1d",
      "kind": "wallpaper",
      "brand": "Riley Sheehey",
      "pattern": "Botanical Cream Wallpaper",
      "colorway": "",
      "room": "Nursery",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2025",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/riley-shinney-botanical-cream-wallpaper-dn1d-qhc.jpg",
        "photos/riley-shinney-botanical-cream-wallpaper-dn1d-0v5.jpg"
      ],
      "cover": 0,
      "photo": "photos/riley-shinney-botanical-cream-wallpaper-dn1d-qhc.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxhb6voa20ci",
      "kind": "before_after",
      "brand": "Sarah Von Dreele",
      "pattern": "Beth",
      "colorway": "Cream",
      "room": "Kids room",
      "style": "Patter Rapeat",
      "project": "",
      "city": "San Anselmo",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/sarah-von-dreele-beth-20ci-after-hi3.jpg"
      ],
      "cover": 0,
      "photo": "photos/sarah-von-dreele-beth-20ci-after-hi3.jpg",
      "beforePhotos": [
        "photos/sarah-von-dreele-beth-20ci-before-k6g.jpg",
        "photos/sarah-von-dreele-beth-20ci-before-hn0.jpg",
        "photos/sarah-von-dreele-beth-20ci-before-dp9.jpg",
        "photos/sarah-von-dreele-beth-20ci-before-ywq.jpg"
      ],
      "afterPhotos": [
        "photos/sarah-von-dreele-beth-20ci-after-hi3.jpg",
        "photos/sarah-von-dreele-beth-20ci-after-hf4.jpg",
        "photos/sarah-von-dreele-beth-20ci-after-oml.jpg",
        "photos/sarah-von-dreele-beth-20ci-after-fbz.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "photos/sarah-von-dreele-beth-20ci-before-k6g.jpg",
      "afterPhoto": "photos/sarah-von-dreele-beth-20ci-after-hi3.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "msxnwgzdon3s7",
      "kind": "before_after",
      "brand": "Happy Wall",
      "pattern": "Dandelion Dreamscape",
      "colorway": "",
      "room": "Bathroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Mateo",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/happy-wall-dandelion-dreamscape-n3s7-after-ovb.jpg"
      ],
      "cover": 0,
      "photo": "photos/happy-wall-dandelion-dreamscape-n3s7-after-ovb.jpg",
      "beforePhotos": [
        "photos/happy-wall-dandelion-dreamscape-n3s7-before-2v7.jpg",
        "photos/happy-wall-dandelion-dreamscape-n3s7-before-730.jpg",
        "photos/happy-wall-dandelion-dreamscape-n3s7-before-c83.jpg",
        "photos/happy-wall-dandelion-dreamscape-n3s7-before-741.jpg"
      ],
      "afterPhotos": [
        "photos/happy-wall-dandelion-dreamscape-n3s7-after-ovb.jpg",
        "photos/happy-wall-dandelion-dreamscape-n3s7-after-v2p.jpg",
        "photos/happy-wall-dandelion-dreamscape-n3s7-after-pil.jpg",
        "photos/happy-wall-dandelion-dreamscape-n3s7-after-st1.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "photos/happy-wall-dandelion-dreamscape-n3s7-before-2v7.jpg",
      "afterPhoto": "photos/happy-wall-dandelion-dreamscape-n3s7-after-ovb.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "msxpglzgg4kwd",
      "kind": "wallpaper",
      "brand": "Cowtan & Tout",
      "pattern": "Pompano Wallpaper",
      "colorway": "",
      "room": "Home office",
      "style": "Grasscloth & texture",
      "project": "",
      "city": "Mill Valley",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/cowtan-tout-pompano-wallpaper-4kwd-hez.jpg",
        "photos/cowtan-tout-pompano-wallpaper-4kwd-cm5.jpg",
        "photos/cowtan-tout-pompano-wallpaper-4kwd-nge.jpg",
        "photos/cowtan-tout-pompano-wallpaper-4kwd-1xh.jpg"
      ],
      "cover": 0,
      "photo": "photos/cowtan-tout-pompano-wallpaper-4kwd-hez.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxpixayd0i1y",
      "kind": "before_after",
      "brand": "Cowtan & Tout",
      "pattern": "Pompano Wallpaper",
      "colorway": "",
      "room": "Home office",
      "style": "Grasscloth & texture",
      "project": "",
      "city": "Mill Valley",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/cowtan-tout-pompano-wallpaper-0i1y-after-hmj.jpg"
      ],
      "cover": 0,
      "photo": "photos/cowtan-tout-pompano-wallpaper-0i1y-after-hmj.jpg",
      "beforePhotos": [
        "photos/cowtan-tout-pompano-wallpaper-0i1y-before-g7v.jpg",
        "photos/cowtan-tout-pompano-wallpaper-0i1y-before-ezs.jpg",
        "photos/cowtan-tout-pompano-wallpaper-0i1y-before-4ti.jpg"
      ],
      "afterPhotos": [
        "photos/cowtan-tout-pompano-wallpaper-0i1y-after-196.jpg",
        "photos/cowtan-tout-pompano-wallpaper-0i1y-after-9bl.jpg",
        "photos/cowtan-tout-pompano-wallpaper-0i1y-after-3dr.jpg",
        "photos/cowtan-tout-pompano-wallpaper-0i1y-after-hmj.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 3,
      "beforePhoto": "photos/cowtan-tout-pompano-wallpaper-0i1y-before-g7v.jpg",
      "afterPhoto": "photos/cowtan-tout-pompano-wallpaper-0i1y-after-hmj.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "msxpphbco8i24",
      "kind": "wallpaper",
      "brand": "Arte",
      "pattern": "Arte Antigua Stagionato",
      "colorway": "33010 Foliage.",
      "room": "Bathroom",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/arte-arte-antigua-stagionato-8i24-fg5.jpg",
        "photos/arte-arte-antigua-stagionato-8i24-cc1.jpg",
        "photos/arte-arte-antigua-stagionato-8i24-ooq.jpg",
        "photos/arte-arte-antigua-stagionato-8i24-aqm.jpg",
        "photos/arte-arte-antigua-stagionato-8i24-yjk.jpg",
        "photos/arte-arte-antigua-stagionato-8i24-utz.jpg"
      ],
      "cover": 0,
      "photo": "photos/arte-arte-antigua-stagionato-8i24-fg5.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxq8y0q9pi9i",
      "kind": "wallpaper",
      "brand": "Schumacher",
      "pattern": "Schumacher Tasmanian Mimosa",
      "colorway": "",
      "room": "Bathroom",
      "style": "Floral",
      "project": "",
      "city": "Mill Valley",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/schumacher-schumacher-tasmanian-mimosa-pi9i-a54.jpg",
        "photos/schumacher-schumacher-tasmanian-mimosa-pi9i-cw2.jpg",
        "photos/schumacher-schumacher-tasmanian-mimosa-pi9i-ts4.jpg",
        "photos/schumacher-schumacher-tasmanian-mimosa-pi9i-nca.jpg",
        "photos/schumacher-schumacher-tasmanian-mimosa-pi9i-n5g.jpg"
      ],
      "cover": 2,
      "photo": "photos/schumacher-schumacher-tasmanian-mimosa-pi9i-ts4.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxqzqjgxae4o",
      "kind": "wallpaper",
      "brand": "Phillip Jeffries",
      "pattern": "All Wound Up",
      "colorway": "Navy Check",
      "room": "Bedroom",
      "style": "Grasscloth & texture",
      "project": "",
      "city": "San Anselmo",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/phillip-jeffries-all-wound-up-ae4o-jst.jpg",
        "photos/phillip-jeffries-all-wound-up-ae4o-5um.jpg",
        "photos/phillip-jeffries-all-wound-up-ae4o-p8q.jpg",
        "photos/phillip-jeffries-all-wound-up-ae4o-6xo.jpg",
        "photos/phillip-jeffries-all-wound-up-ae4o-xhn.jpg",
        "photos/phillip-jeffries-all-wound-up-ae4o-swr.jpg",
        "photos/phillip-jeffries-all-wound-up-ae4o-e3h.jpg",
        "photos/phillip-jeffries-all-wound-up-ae4o-378.jpg"
      ],
      "cover": 0,
      "photo": "photos/phillip-jeffries-all-wound-up-ae4o-jst.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxscq8n82c5c",
      "kind": "wallpaper",
      "brand": "Phillip Jeffries",
      "pattern": "Extra Fine Arrowroot",
      "colorway": "Key West",
      "room": "Living room",
      "style": "Grasscloth & texture",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/phillip-jeffries-extra-fine-arrowroot-2c5c-lxd.jpg",
        "photos/phillip-jeffries-extra-fine-arrowroot-2c5c-g9r.jpg",
        "photos/phillip-jeffries-extra-fine-arrowroot-2c5c-lpj.jpg"
      ],
      "cover": 1,
      "photo": "photos/phillip-jeffries-extra-fine-arrowroot-2c5c-g9r.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxsoplm8rwaj",
      "kind": "wallpaper",
      "brand": "Sarah Von Dreele",
      "pattern": "Beth",
      "colorway": "Cream",
      "room": "Kids room",
      "style": "Floral",
      "project": "",
      "city": "San Anselmo",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/sarah-von-dreele-beth-rwaj-99o.jpg",
        "photos/sarah-von-dreele-beth-rwaj-rzv.jpg",
        "photos/sarah-von-dreele-beth-rwaj-flj.jpg",
        "photos/sarah-von-dreele-beth-rwaj-yu6.jpg"
      ],
      "cover": 1,
      "photo": "photos/sarah-von-dreele-beth-rwaj-rzv.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxud0d5csf3m",
      "kind": "wallpaper",
      "brand": "Riley Sheehey",
      "pattern": "English Garden Stripe",
      "colorway": "",
      "room": "Nursery",
      "style": "Pattern Repeat",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/riley-sheehey-english-garden-stripe-sf3m-fmp.jpg",
        "photos/riley-sheehey-english-garden-stripe-sf3m-8x1.jpg",
        "photos/riley-sheehey-english-garden-stripe-sf3m-d38.jpg",
        "photos/riley-sheehey-english-garden-stripe-sf3m-lvm.jpg",
        "photos/riley-sheehey-english-garden-stripe-sf3m-p1t.jpg",
        "photos/riley-sheehey-english-garden-stripe-sf3m-5ju.jpg"
      ],
      "cover": 0,
      "photo": "photos/riley-sheehey-english-garden-stripe-sf3m-fmp.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxumjwyp4bxx",
      "kind": "before_after",
      "brand": "Riley Sheehey",
      "pattern": "English Garden Stripe",
      "colorway": "",
      "room": "Nursery",
      "style": "Pattern Repeat",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/riley-sheehey-english-garden-stripe-4bxx-after-5lo.jpg"
      ],
      "cover": 0,
      "photo": "photos/riley-sheehey-english-garden-stripe-4bxx-after-5lo.jpg",
      "beforePhotos": [
        "photos/riley-sheehey-english-garden-stripe-4bxx-before-ahx.jpg",
        "photos/riley-sheehey-english-garden-stripe-4bxx-before-0me.jpg"
      ],
      "afterPhotos": [
        "photos/riley-sheehey-english-garden-stripe-4bxx-after-5lo.jpg",
        "photos/riley-sheehey-english-garden-stripe-4bxx-after-yky.jpg",
        "photos/riley-sheehey-english-garden-stripe-4bxx-after-df6.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "photos/riley-sheehey-english-garden-stripe-4bxx-before-ahx.jpg",
      "afterPhoto": "photos/riley-sheehey-english-garden-stripe-4bxx-after-5lo.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "msxv9tuepieeh",
      "kind": "wallpaper",
      "brand": "Spoonflower",
      "pattern": "Luxurious Vintage Floral Ornament",
      "colorway": "Gold And Midnight Blue",
      "room": "Living room",
      "style": "Pattern Repeat",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/spoonflower-luxurious-vintage-floral-ornament-ieeh-5xb.jpg",
        "photos/spoonflower-luxurious-vintage-floral-ornament-ieeh-n2s.jpg",
        "photos/spoonflower-luxurious-vintage-floral-ornament-ieeh-sd2.jpg",
        "photos/spoonflower-luxurious-vintage-floral-ornament-ieeh-ju4.jpg"
      ],
      "cover": 0,
      "photo": "photos/spoonflower-luxurious-vintage-floral-ornament-ieeh-5xb.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msxvfsjjio8lf",
      "kind": "before_after",
      "brand": "Spoonflower",
      "pattern": "Luxurious Vintage Floral Ornament",
      "colorway": "Gold And Midnight Blue",
      "room": "Living room",
      "style": "Pattern Repeat",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-after-8uh.jpg"
      ],
      "cover": 0,
      "photo": "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-after-8uh.jpg",
      "beforePhotos": [
        "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-before-hs3.jpg",
        "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-before-3oo.jpg"
      ],
      "afterPhotos": [
        "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-after-8uh.jpg",
        "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-after-tdr.jpg",
        "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-after-r09.jpg",
        "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-after-y7a.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-before-hs3.jpg",
      "afterPhoto": "photos/spoonflower-luxurious-vintage-floral-ornament-o8lf-after-8uh.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "mszdjoz2vwdg3",
      "kind": "wallpaper",
      "brand": "Wallism",
      "pattern": "Summer Birch",
      "colorway": "",
      "room": "Guest bedroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "Agua Caliente",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/wallism-summer-birch-wdg3-bfj.jpg",
        "photos/wallism-summer-birch-wdg3-i53.jpg",
        "photos/wallism-summer-birch-wdg3-3un.jpg",
        "photos/wallism-summer-birch-wdg3-u5u.jpg",
        "photos/wallism-summer-birch-wdg3-zs7.jpg",
        "photos/wallism-summer-birch-wdg3-hup.jpg",
        "photos/wallism-summer-birch-wdg3-yvo.jpg"
      ],
      "cover": 0,
      "photo": "photos/wallism-summer-birch-wdg3-bfj.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mszdn89g7uy33",
      "kind": "before_after",
      "brand": "Wallism",
      "pattern": "Summer Birch",
      "colorway": "",
      "room": "Guest bedroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "Agua Caliente",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/wallism-summer-birch-uy33-after-bdp.jpg"
      ],
      "cover": 0,
      "photo": "photos/wallism-summer-birch-uy33-after-bdp.jpg",
      "beforePhotos": [
        "photos/wallism-summer-birch-uy33-before-kr5.jpg",
        "photos/wallism-summer-birch-uy33-before-8g3.jpg",
        "photos/wallism-summer-birch-uy33-before-twt.jpg"
      ],
      "afterPhotos": [
        "photos/wallism-summer-birch-uy33-after-bdp.jpg",
        "photos/wallism-summer-birch-uy33-after-f2t.jpg",
        "photos/wallism-summer-birch-uy33-after-1f0.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "photos/wallism-summer-birch-uy33-before-kr5.jpg",
      "afterPhoto": "photos/wallism-summer-birch-uy33-after-bdp.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "mt1ma42yb9sgt",
      "kind": "wallpaper",
      "brand": "Phillip Jeffries",
      "pattern": "Soho Hemp",
      "colorway": "Concrete Jungle",
      "room": "Media room",
      "style": "Grasscloth & texture",
      "project": "",
      "city": "El Granada",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/phillip-jeffries-soho-hemp-9sgt-103.jpg",
        "photos/phillip-jeffries-soho-hemp-9sgt-1a7.jpg",
        "photos/phillip-jeffries-soho-hemp-9sgt-3dl.jpg",
        "photos/phillip-jeffries-soho-hemp-9sgt-24p.jpg",
        "photos/phillip-jeffries-soho-hemp-9sgt-85s.jpg",
        "photos/phillip-jeffries-soho-hemp-9sgt-wqc.jpg"
      ],
      "cover": 0,
      "photo": "photos/phillip-jeffries-soho-hemp-9sgt-103.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mt1mfkyljnahu",
      "kind": "wallpaper",
      "brand": "Fayce",
      "pattern": "Lapel",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Geometric",
      "project": "",
      "city": "El Granada",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/fayce-lapel-nahu-s9i.jpg",
        "photos/fayce-lapel-nahu-tcd.jpg",
        "photos/fayce-lapel-nahu-vcc.jpg",
        "photos/fayce-lapel-nahu-hie.jpg",
        "photos/fayce-lapel-nahu-bkc.jpg",
        "photos/fayce-lapel-nahu-ehw.jpg"
      ],
      "cover": 0,
      "photo": "photos/fayce-lapel-nahu-s9i.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mt1n13hwnap5b",
      "kind": "wallpaper",
      "brand": "Coordonné",
      "pattern": "Coordonné Bank of Fish Wallpaper",
      "colorway": "Swan",
      "room": "Dining room",
      "style": "Pattern Repeat",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/coordonne-coordonne-bank-of-fish-wallpaper-ap5b-qwk.jpg",
        "photos/coordonne-coordonne-bank-of-fish-wallpaper-ap5b-9r1.jpg",
        "photos/coordonne-coordonne-bank-of-fish-wallpaper-ap5b-0tz.jpg",
        "photos/coordonne-coordonne-bank-of-fish-wallpaper-ap5b-cpu.jpg"
      ],
      "cover": 0,
      "photo": "photos/coordonne-coordonne-bank-of-fish-wallpaper-ap5b-qwk.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mt7cm4nfev31h",
      "kind": "wallpaper",
      "brand": "SARAH JESSICA PARKER & wallshøppe.",
      "pattern": "Purveyor of hip",
      "colorway": "",
      "room": "Living room",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-v31h-5jz.jpg",
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-v31h-1mb.jpg",
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-v31h-7do.jpg",
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-v31h-cj3.jpg"
      ],
      "cover": 0,
      "photo": "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-v31h-5jz.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mt7crgbrpx2um",
      "kind": "wallpaper",
      "brand": "CARLISLE . & CO.",
      "pattern": "Fusion Edge",
      "colorway": "Sandstone",
      "room": "Primary bathroom",
      "style": "Chinoiserie",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/carlisle-co-fusion-edge-x2um-o2x.jpg",
        "photos/carlisle-co-fusion-edge-x2um-i06.jpg",
        "photos/carlisle-co-fusion-edge-x2um-ubo.jpg",
        "photos/carlisle-co-fusion-edge-x2um-ymz.jpg",
        "photos/carlisle-co-fusion-edge-x2um-ye4.jpg",
        "photos/carlisle-co-fusion-edge-x2um-2h4.jpg"
      ],
      "cover": 0,
      "photo": "photos/carlisle-co-fusion-edge-x2um-o2x.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mt7d8c28vaplq",
      "kind": "before_after",
      "brand": "CARLISLE . & CO.",
      "pattern": "Fusion Edge",
      "colorway": "Sandstone",
      "room": "Primary bathroom",
      "style": "Chinoiserie",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/carlisle-co-fusion-edge-aplq-after-4ln.jpg"
      ],
      "cover": 0,
      "photo": "photos/carlisle-co-fusion-edge-aplq-after-4ln.jpg",
      "beforePhotos": [
        "photos/carlisle-co-fusion-edge-aplq-before-g3j.jpg",
        "photos/carlisle-co-fusion-edge-aplq-before-3es.jpg",
        "photos/carlisle-co-fusion-edge-aplq-before-133.jpg",
        "photos/carlisle-co-fusion-edge-aplq-before-sc9.jpg",
        "photos/carlisle-co-fusion-edge-aplq-before-55t.jpg",
        "photos/carlisle-co-fusion-edge-aplq-before-j0b.jpg"
      ],
      "afterPhotos": [
        "photos/carlisle-co-fusion-edge-aplq-after-4ln.jpg",
        "photos/carlisle-co-fusion-edge-aplq-after-azv.jpg",
        "photos/carlisle-co-fusion-edge-aplq-after-sht.jpg",
        "photos/carlisle-co-fusion-edge-aplq-after-1r2.jpg",
        "photos/carlisle-co-fusion-edge-aplq-after-quc.jpg",
        "photos/carlisle-co-fusion-edge-aplq-after-0qz.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "photos/carlisle-co-fusion-edge-aplq-before-g3j.jpg",
      "afterPhoto": "photos/carlisle-co-fusion-edge-aplq-after-4ln.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "mt7dewta1rzrt",
      "kind": "before_after",
      "brand": "Sarah Jessica Parker & wallshøppe.",
      "pattern": "Purveyor of hip",
      "colorway": "",
      "room": "Living room",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-after-lx6.jpg"
      ],
      "cover": 0,
      "photo": "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-after-lx6.jpg",
      "beforePhotos": [
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-before-8pq.jpg",
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-before-dhj.jpg"
      ],
      "afterPhotos": [
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-after-lx6.jpg",
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-after-j9r.jpg",
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-after-w5s.jpg",
        "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-after-3fq.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-before-8pq.jpg",
      "afterPhoto": "photos/sarah-jessica-parker-wallsh-ppe-purveyor-of-hip-rzrt-after-lx6.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "mtbxgwio2h38c",
      "kind": "wallpaper",
      "brand": "Rebel Walls",
      "pattern": "Cuddle Clouds",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/rebel-walls-cuddle-clouds-h38c-yp2.jpg",
        "photos/rebel-walls-cuddle-clouds-h38c-kya.jpg",
        "photos/rebel-walls-cuddle-clouds-h38c-7yx.jpg",
        "photos/rebel-walls-cuddle-clouds-h38c-24n.jpg",
        "photos/rebel-walls-cuddle-clouds-h38c-vhf.jpg",
        "photos/rebel-walls-cuddle-clouds-h38c-npn.jpg"
      ],
      "cover": 0,
      "photo": "photos/rebel-walls-cuddle-clouds-h38c-yp2.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mtbxq0fxzkmfj",
      "kind": "wallpaper",
      "brand": "Cork",
      "pattern": "Single stripe",
      "colorway": "",
      "room": "Kitchen",
      "style": "Acoustic",
      "project": "",
      "city": "",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/cork-single-stripe-kmfj-eto.jpg",
        "photos/cork-single-stripe-kmfj-ppy.jpg"
      ],
      "cover": 0,
      "photo": "photos/cork-single-stripe-kmfj-eto.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mtbxrn8mflnfl",
      "kind": "before_after",
      "brand": "Cork",
      "pattern": "Single stripe",
      "colorway": "",
      "room": "Kitchen",
      "style": "Acoustic",
      "project": "",
      "city": "",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/cork-single-stripe-lnfl-after-oo0.jpg"
      ],
      "cover": 0,
      "photo": "photos/cork-single-stripe-lnfl-after-oo0.jpg",
      "beforePhotos": [
        "photos/cork-single-stripe-lnfl-before-von.jpg",
        "photos/cork-single-stripe-lnfl-before-zs4.jpg"
      ],
      "afterPhotos": [
        "photos/cork-single-stripe-lnfl-after-oo0.jpg",
        "photos/cork-single-stripe-lnfl-after-9yk.jpg"
      ],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "photos/cork-single-stripe-lnfl-before-von.jpg",
      "afterPhoto": "photos/cork-single-stripe-lnfl-after-oo0.jpg",
      "workType": "wallpaper"
    },
    {
      "id": "mtiq2b1vgbap6",
      "kind": "wallpaper",
      "brand": "Graham & Brown",
      "pattern": "Palazzo",
      "colorway": "Verde",
      "room": "Powder room",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/graham-brown-palazzo-bap6-xwi.jpg",
        "photos/graham-brown-palazzo-bap6-r58.jpg",
        "photos/graham-brown-palazzo-bap6-xna.jpg"
      ],
      "cover": 0,
      "photo": "photos/graham-brown-palazzo-bap6-xwi.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mtiqgy709jbjz",
      "kind": "wallpaper",
      "brand": "Common Room",
      "pattern": "Climbing Curios",
      "colorway": "",
      "room": "Primary bathroom",
      "style": "Stripe & Ribbon",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/anna-french-climbing-curios-jbjz-2fb.jpg",
        "photos/anna-french-climbing-curios-jbjz-08j.jpg",
        "photos/anna-french-climbing-curios-jbjz-aud.jpg",
        "photos/anna-french-climbing-curios-jbjz-x6f.jpg"
      ],
      "cover": 0,
      "photo": "photos/anna-french-climbing-curios-jbjz-2fb.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mtir5mcgdxrwy",
      "kind": "wallpaper",
      "brand": "Spoonflower",
      "pattern": "Wallpaper in Magnolia Way",
      "colorway": "Navy/White Linen",
      "room": "Primary bedroom",
      "style": "Grasscloth & texture",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/spoonflower-wallpaper-in-magnolia-way-xrwy-y2m.jpg",
        "photos/spoonflower-wallpaper-in-magnolia-way-xrwy-xwg.jpg",
        "photos/spoonflower-wallpaper-in-magnolia-way-xrwy-shg.jpg"
      ],
      "cover": 0,
      "photo": "photos/spoonflower-wallpaper-in-magnolia-way-xrwy-y2m.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mtirjhcx3oywg",
      "kind": "wallpaper",
      "brand": "Timorous Beasties",
      "pattern": "Omni Splatt Wallpaper",
      "colorway": "Orange",
      "room": "Water closet",
      "style": "Damask",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/timorous-beasties-omni-splatt-wallpaper-oywg-mc2.jpg",
        "photos/timorous-beasties-omni-splatt-wallpaper-oywg-2ij.jpg",
        "photos/timorous-beasties-omni-splatt-wallpaper-oywg-3to.jpg",
        "photos/timorous-beasties-omni-splatt-wallpaper-oywg-pfq.jpg",
        "photos/timorous-beasties-omni-splatt-wallpaper-oywg-uin.jpg"
      ],
      "cover": 0,
      "photo": "photos/timorous-beasties-omni-splatt-wallpaper-oywg-mc2.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mtirnlfy4a52s",
      "kind": "wallpaper",
      "brand": "Cole & Son",
      "pattern": "Melville",
      "colorway": "",
      "room": "Water closet",
      "style": "Metallic",
      "project": "",
      "city": "Tiburon",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/cole-son-melville-a52s-1sw.jpg",
        "photos/cole-son-melville-a52s-djn.jpg",
        "photos/cole-son-melville-a52s-zfy.jpg",
        "photos/cole-son-melville-a52s-hvx.jpg",
        "photos/cole-son-melville-a52s-8qc.jpg",
        "photos/cole-son-melville-a52s-9w4.jpg"
      ],
      "cover": 2,
      "photo": "photos/cole-son-melville-a52s-zfy.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mtis52a7wfatp",
      "kind": "wallpaper",
      "brand": "Dedar",
      "pattern": "Schwarzwald Wall",
      "colorway": "001",
      "room": "Alcove",
      "style": "Chinoiserie",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/dedar-schwarzwald-wall-fatp-6rj.jpg",
        "photos/dedar-schwarzwald-wall-fatp-to7.jpg",
        "photos/dedar-schwarzwald-wall-fatp-8re.jpg",
        "photos/dedar-schwarzwald-wall-fatp-zss.jpg",
        "photos/dedar-schwarzwald-wall-fatp-9gq.jpg"
      ],
      "cover": 2,
      "photo": "photos/dedar-schwarzwald-wall-fatp-8re.jpg",
      "beforePhotos": [],
      "afterPhotos": [],
      "beforeCover": 0,
      "afterCover": 0,
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    }
  ]
};
