window.PARFAIT_CATALOGUE = {
  "version": 1,
  "updated": "2026-08-15T18:39:33.084Z",
  "items": [
    {
      "id": "msgp527nmr7my",
      "kind": "wallpaper",
      "brand": "York Wallcoverings",
      "pattern": "Antonina Vella Deco Speakeasy",
      "colorway": "",
      "room": "Office",
      "style": "Metallic",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/york-wallcoverings-antonina-vella-deco-speakeasy-r7my.jpg",
        "photos/york-wallcoverings-antonina-vella-deco-speakeasy-r7my-bw7.jpg",
        "photos/york-wallcoverings-antonina-vella-deco-speakeasy-r7my-hsc.jpg"
      ],
      "cover": 1,
      "photo": "photos/york-wallcoverings-antonina-vella-deco-speakeasy-r7my-bw7.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msgqt1vq5xyi2",
      "kind": "wallpaper",
      "brand": "Wallism",
      "pattern": "Ukiyo-e Clouds, Blues wallpaper mural",
      "colorway": "",
      "room": "Living room",
      "style": "Mural & scenic",
      "project": "",
      "city": "Atherton",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2.jpg",
        "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2-3rd.jpg",
        "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2-4o7.jpg",
        "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2-1k2.jpg"
      ],
      "cover": 0,
      "photo": "photos/wallism-ukiyo-e-clouds-blues-wallpaper-mural-xyi2.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msqeu91xtlx2t",
      "kind": "wallpaper",
      "brand": "Kelly Ventura",
      "pattern": "Marsh in Lagoon",
      "colorway": "",
      "room": "Living room",
      "style": "Floral",
      "project": "",
      "city": "Belmont",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-jev.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-hsa.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-0il.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-o04.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-9w8.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-41q.jpg",
        "photos/kelly-ventura-marsh-in-lagoon-lx2t-w1l.jpg"
      ],
      "cover": 3,
      "photo": "photos/kelly-ventura-marsh-in-lagoon-lx2t-o04.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msrm2hpqkvfom",
      "kind": "wallpaper",
      "brand": "York Wallcoverings",
      "pattern": "York Modern Heritage Yarrow Nouveau",
      "colorway": "Charcoal & Gold",
      "room": "Primary bedroom",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/york-wallcoverings-york-modern-heritage-yarrow-nouveau-vfom-y09.jpg",
        "photos/york-wallcoverings-york-modern-heritage-yarrow-nouveau-vfom-n1t.jpg",
        "photos/york-wallcoverings-york-modern-heritage-yarrow-nouveau-vfom-28n.jpg"
      ],
      "cover": 0,
      "photo": "photos/york-wallcoverings-york-modern-heritage-yarrow-nouveau-vfom-y09.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msrmoagz15cu4",
      "kind": "wallpaper",
      "brand": "York Wallcoverings",
      "pattern": "Gwendolyn Wallpaper - Magnolia Home collection by Joanna Gaines,",
      "colorway": "",
      "room": "Laundry room",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-xnd.jpg",
        "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-tpv.jpg",
        "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-yht.jpg",
        "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-rm3.jpg"
      ],
      "cover": 0,
      "photo": "photos/york-wallcoverings-gwendolyn-wallpaper-magnolia-home-collection-5cu4-xnd.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "msrowrdmrh7dx",
      "kind": "wallpaper",
      "brand": "Phillip Jeffries",
      "pattern": "Fuji Weave - Fresh Stream",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Grasscloth & texture",
      "project": "",
      "city": "Corte Madera",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-9t9.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-8pj.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-k1e.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-i1w.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-7gi.jpg",
        "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-eg7.jpg"
      ],
      "cover": 2,
      "photo": "photos/phillip-jeffries-fuji-weave-fresh-stream-h7dx-k1e.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss0m5aiji456",
      "kind": "wallpaper",
      "brand": "Happy Wall",
      "pattern": "Dandelion Dreamscape",
      "colorway": "",
      "room": "Bathroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Mateo",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/happy-wall-dandelion-dreamscape-i456-uji.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-v31.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-3yj.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-gkp.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-5sw.jpg",
        "photos/happy-wall-dandelion-dreamscape-i456-jip.jpg"
      ],
      "cover": 0,
      "photo": "photos/happy-wall-dandelion-dreamscape-i456-uji.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss1jilh0x9nl",
      "kind": "wallpaper",
      "brand": "Phillip Jeffries",
      "pattern": "Aura Ivory",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Rafael - Marinwood",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/phillip-jeffries-aura-ivory-x9nl-ceh.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-sh1.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-n14.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-nyi.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-cul.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-gnt.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-py8.jpg",
        "photos/phillip-jeffries-aura-ivory-x9nl-k6m.jpg"
      ],
      "cover": 0,
      "photo": "photos/phillip-jeffries-aura-ivory-x9nl-ceh.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss1scrkeqby5",
      "kind": "wallpaper",
      "brand": "Spoonflower",
      "pattern": "Art Deco Swans",
      "colorway": "Black on cream",
      "room": "Sitting room",
      "style": "Pattern",
      "project": "",
      "city": "",
      "year": "2025",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/spoonflower-art-deco-swans-qby5-ije.jpg",
        "photos/spoonflower-art-deco-swans-qby5-9sl.jpg",
        "photos/spoonflower-art-deco-swans-qby5-ze5.jpg",
        "photos/spoonflower-art-deco-swans-qby5-p0j.jpg"
      ],
      "cover": 0,
      "photo": "photos/spoonflower-art-deco-swans-qby5-ije.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss24arga0pmm",
      "kind": "wallpaper",
      "brand": "Hygge & West",
      "pattern": "Underwater World Wallpaper",
      "colorway": "Deep Blue",
      "room": "Guest bathroom",
      "style": "Metallic",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/hygge-west-underwater-world-wallpaper-0pmm-rqm.jpg",
        "photos/hygge-west-underwater-world-wallpaper-0pmm-akt.jpg",
        "photos/hygge-west-underwater-world-wallpaper-0pmm-9ab.jpg",
        "photos/hygge-west-underwater-world-wallpaper-0pmm-x82.jpg"
      ],
      "cover": 3,
      "photo": "photos/hygge-west-underwater-world-wallpaper-0pmm-x82.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss2ft9wam76c",
      "kind": "wallpaper",
      "brand": "Sandberg",
      "pattern": "Klint Misty Blue Wallpaper Mural",
      "colorway": "",
      "room": "Office",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/sandberg-klint-misty-blue-wallpaper-mural-m76c-2fq.jpg",
        "photos/sandberg-klint-misty-blue-wallpaper-mural-m76c-6e5.jpg"
      ],
      "cover": 0,
      "photo": "photos/sandberg-klint-misty-blue-wallpaper-mural-m76c-2fq.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss2lbajqqjo4",
      "kind": "wallpaper",
      "brand": "Rebel Walls",
      "pattern": "Flowing Hills",
      "colorway": "Green",
      "room": "Office",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Francisco",
      "year": "2026",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/rebel-walls-flowing-hills-qjo4-x8p.jpg",
        "photos/rebel-walls-flowing-hills-qjo4-869.jpg",
        "photos/rebel-walls-flowing-hills-qjo4-wcp.jpg",
        "photos/rebel-walls-flowing-hills-qjo4-8uj.jpg",
        "photos/rebel-walls-flowing-hills-qjo4-oq0.jpg"
      ],
      "cover": 0,
      "photo": "photos/rebel-walls-flowing-hills-qjo4-x8p.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss2ww0p7xrp9",
      "kind": "wallpaper",
      "brand": "York Wallcoverings",
      "pattern": "Judarn Floral Mural",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Mural & scenic",
      "project": "2025",
      "city": "",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/york-wallcoverings-judarn-floral-mural-2025-xrp9-7xl.jpg",
        "photos/york-wallcoverings-judarn-floral-mural-2025-xrp9-0uo.jpg",
        "photos/york-wallcoverings-judarn-floral-mural-2025-xrp9-dfc.jpg"
      ],
      "cover": 0,
      "photo": "photos/york-wallcoverings-judarn-floral-mural-2025-xrp9-7xl.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss31howbaabb",
      "kind": "wallpaper",
      "brand": "Belarte",
      "pattern": "Vintage Landscape",
      "colorway": "",
      "room": "Primary bedroom",
      "style": "Mural & scenic",
      "project": "",
      "city": "San Francisco",
      "year": "",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/belarte-vintage-landscape-aabb-ixc.jpg",
        "photos/belarte-vintage-landscape-aabb-l4t.jpg",
        "photos/belarte-vintage-landscape-aabb-91q.jpg"
      ],
      "cover": 2,
      "photo": "photos/belarte-vintage-landscape-aabb-91q.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    },
    {
      "id": "mss7d96dndn1d",
      "kind": "wallpaper",
      "brand": "Riley Shinney",
      "pattern": "Botanical Cream Wallpaper",
      "colorway": "",
      "room": "Nursery",
      "style": "Floral",
      "project": "",
      "city": "",
      "year": "2025",
      "panels": "",
      "notes": "",
      "photos": [
        "photos/riley-shinney-botanical-cream-wallpaper-dn1d-qhc.jpg",
        "photos/riley-shinney-botanical-cream-wallpaper-dn1d-0v5.jpg"
      ],
      "cover": 0,
      "photo": "photos/riley-shinney-botanical-cream-wallpaper-dn1d-qhc.jpg",
      "beforePhoto": "",
      "afterPhoto": "",
      "workType": ""
    }
  ]
};
