/* Parfait Wallpaper Services — catalogue
   Generated by the Manage catalogue screen. Replace this whole file
   when you publish; do not edit it by hand. Photographs referenced
   here live in the photos/ folder beside it. */
window.PARFAIT_CATALOGUE = {
  "version": 1,
  "updated": "2026-08-05",
  "items": []
};
